apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi # default AKS provisioned storage class in my AKS Cluster
  resources:
    requests:
      storage: 5Gi